kind: assertion
apiVersion: api.webmethods.io/beta
metadata:
  name: assertion vcs
  namespace: demo-vcs
  version: '1.0'
  tags: []
spec:
  - name: EWVQWV
    key: __response__
    value: EWHVQH
    action: notHaveProperty
  - name: EWVQWV
    key: __response__
    value: EWHVQH
    action: notHaveProperty
  - name: EWVQWV
    key: __response_headers__
    value: EWHVQH
    action: equals
