#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: HTTPEndpoint
apiVersion: api.webmethods.io/beta
metadata:
  name: endpoint
  version: alpha
  namespace: thor
  tags:
    - tags
spec:
  url: http://petstore.swagger.io
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
