#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: TransformResponse
apiVersion: api.webmethods.io/beta
metadata:
  namespace: thor
  name: response_processing_policy
  version: alpha
spec:
  condition: (${response.headers.name} equals svis)
  transformations:
    set:
      - key: ${response.headers.h2}
        value: test-header-value
    setStatus: # Introduced for Response Processing
       code: 40
       message: Invalid request
    setPayload:
      content-types:
        - application/xml: <test></test>
      xsl:
        - $path: format.xsl
    remove:
      - ${response.headers.name}
