#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
---
kind: InboundBulkHead
apiVersion: api.webmethods.io/beta
metadata:
  name: transport_bulkhead
  version: 1
  namespace: sample
spec:
  maxConcurrentCalls: 20
  enableBulkheadForCallbacks:
    maxConcurrentCallbacks: 30
  retryAfterResponseHeader:
    retryAfterValue: 100  #in seconds
