#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: SetContextVariable
apiVersion: api.webmethods.io/beta
metadata:
  name: Custom Extension Policy
  version: 1
  spec:
    enabled: true 
    condition: |
      (${request.httpMethod} equals POST) or 
      (${request.headers.name} notEquals ${request.payload.jsonPath[$.customer.name]})
    # other operators include Equals, Equals ignore case, Not equals, Not equals ignore case, Contains, Not Contains, Exists, Not Exists, IP Range, Greater Than, Lesser Than
    variable:
      - name: customerName
        value: ${request.headers.h1}
      - name: customerName
        value: ${request.payload.xpath[/s:sdd/sd]}
    namespaces:
      - prefix: s
        URI: http://test.com