#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: CacheServiceResult
apiVersion: api.ibm.com/v1
metadata:
    name: service_cache
    version: 1.0
    namespace: sample
    tags:
        - cache
        - service
        - result
        - monitoring
        - policy
spec:
  condition: (${request.headers.test} equals test1) or (${request.query.test} equals test1}) # operator contains can also be used
  ttl: 4d # m,h,d,w,cw, cm are possible values
  enabled: true
  maxSize: 32kb