#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: RateLimiter
apiVersion: api.ibm.com/v1
metadata:
  name: rate-limiter
  version: 1.0
  namespace: sample
  tags:
    - traffic_optimization
spec:
  enabled: true
  maxLimit: 20
  applications:
      - "Each-applications" 
  applicationSpecific: true
  alert-configuration:
    interval: 2m  # m,h,d,w,cw, cm are possible values
    frequency: always # Other possible value is 'once'
    message: 'Throtting reached!'
  destination:
    - api_gateway
    - dev_portals
    - email:
        - nas@sag.com
        - daso@sag.com
    - snmp
    - jdbc
    - centraSite
    - elasticsearch
    - log-file:
        level: info 
  