apiVersion: api.ibm.com/v1
kind: Set
metadata:
  name: set-customer-name-var
  namespace: lwgw
spec:
  messageHeader:
    action: 'add' # 'combine' | 'set' | 'add'
    valueType: 'webm-var-expression' # "webm-var-expression"
    headerName: "organisation"
    value: "${request.query.QUERY_NAME}"