kind: ibmcloudlogin
apiVersion: api.ibm.com/v1
metadata:
  name: ibm_cloud_login
  version: 1
  namespace: sample
spec: 
  message: ibm_cloud_login_message #optional
  apikey: "my-api-key-secret" #SHOULD be an alias to the secret not the actual secret
  tlsClientProfile: "tls_profile"