kind: luaScript
apiVersion: api.ibm.com/v1
metadata:
  name: ibm_cloud_login
  version: 1
  namespace: sample
spec: 
    source: |-
      context:run_action('set-var-1')
      context:run_action('my-invoke')
    actions:
      set-var-1:
        setVar:
          messageHeader:
            messageName: request
            headerName: X-Foo
            value: "'foo'"
      my-invoke:
        invoke:
          input: request
          output: response
          endpoint:
            http:
              verb: GET
              target:
                url: $(endpoint)
                timeout: 10