kind: RateLimit
apiVersion: api.ibm.com/v1
metadata:
  name: ratelimit-sample
  version: 1.0
  namespace: sample
spec:
  target: "Subscribed" #optional - default(all), also All, NonSubscribed, Specified<Vec<GroupID>>
  limits: #array of any of below
    - limitDef: #inline in lwgw model -> Naming TBC
        name: "moderate-limit" #required -> the name to give to this rate limit. Make sure its unique!
        definition: 
          $ref: sample:moderate-limit-def:1.0
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        destination:
          - api_gateway
          - dev_portals
          - email:
              - nas@sag.com
              - daso@sag.com
          - snmp
          - jdbc
          - centraSite
          - elasticsearch
          - log-file:
              level: info
          - apic
    lwgw-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        limits: 
          - globalLimit: #called ref in lwgw model. Studio will only support referencing, but not defining ref limits
              name: "database-rate-limit" #-> the rate limit ref needs to be created in APIM or some other amdin view
              operation: "consume"
          - planLimit: #called alias in lwgw model. Studio will only support referencing, but not defining alias limits
              name: "basic-limit" #applied dynamically, based on identified plan -> the rate limit mapping and definition needs to be done in subscription database, and APIM
              operation: "consume"

---
kind: RateLimitDef 
apiVersion: api.ibm.com/v1
metadata:
  name: moderate-limit-def
  version: 1
  namespace: sample
spec:
  consumerSpecific: true #optional, default is false -> called useGroupId in LWGW
  #dynamicValue: "$header('request', 'organisation-name')" #optional, can set a dynamic key to apply this rate limit to. What dynamic values are allowed?
  max: 50 #size of the RL bucket
  intervalLen: 1
  intervalUnit: "second" #minute, hour, day, week, calendarweek, calendarmonth
  #weightExpr: "$variable('workSize')" #optional - dynamic string
  extensions: 
    lw-gateway:
      weightExpr: "$variable('workSize')" #optional - dynamic string
      dynamicValue: "$header('request', 'organisation-name')" #optional, can set a dynamic key to apply this rate limit to. What dynamic values are allowed?

  