kind: AuthorizeUser
apiVersion: api.webmethods.io/beta
metadata:
  name: AuthorizeUser
  namespace: dev
  version: '1.0'
  tags: []
spec:
  users:
    - Administrator
    - ApiFalconz
  groups:
    - webm-api-all
    - webm-api-falconz
  teams:
    - falconz
    - ninox
