kind: PolicySequence
apiVersion: api.webmethods.io/beta
metadata:
  name: vigneshps
  namespace: default
  version: '1.0'
  tags: []
spec:
  transport:
    - $ref: default:vigneshtransport:1.0
  routing:
    - $ref: default:vigneshsr:1.0
