kind: test
apiVersion: api.webmethods.io/v1
metadata:
  name: TestPayments
  version: 1.0.0
  tags:
    - functional123
  namespace: default
spec:
  api:
    $ref: dev:jul101817:1.0
  environment:
    $ref: default:TestPaymentsEnvironment:1.0.0
  request:
    - method: POST
      resource: v2/pet
      headers:
        - key: Content-Type
          value: ${content-type}
      auth:
        noauth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
        $ref: "daso:assertion:alpha"
      payload:
        raw:
          json: |
            {
              "id": 3,
              "category": {
                "id": 0,
                "name": "${dogname}"
              },
              "name": "doggie",
              "photoUrls": [
                "string"
              ],
              "tags": [
                {
                  "id": 0,
                  "name": "string"
                }
              ],
              "status": "available"
            }

    - method: ${method}
      resource: v2/pet
      headers:
        - key: Content-Type
          value: ${content-type}
      auth:
        noauth: true
      settings:
        sslVerification: false
        encodeURL: true
      assertions:
        $ref: "daso:assertion:alpha"
      payload:
        raw:
          json: |
            {
              "id": 0,
              "category": {
                "id": 0,
                "name": "${dogname}"
              },
              "name": "doggie",
              "photoUrls": [
                "string"
              ],
              "tags": [
                {
                  "id": 0,
                  "name": "string"
                }
              ],
              "status": "available"
            }
