kind: PolicySequence
apiVersion: api.webmethods.io/v1
metadata:
  name: scope_policy_sequence
  namespace: dev
  version: '1.0'
  tags:
    - dev_policies
spec:
  transport:
    - $ref: dev:enable_https:1.0
  iam:
    - $ref: dev:identify_and_authorize:1.0
  routing:
    - $ref: dev:my-default-routing:1.0 dev:default-routing:1.0
