kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: default-routing
  version: 1.0
  namespace: dev
  tags:
    - routing
    - route
    - policy
spec:
  default-endpoint:
    $ref: dev:default_endpoint:1.0
